# Generated by Django 4.2.3 on 2023-07-13 04:14

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('exchange_rate', currency.models.CurrencyExchangeField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(default='', max_length=48)),
            ],
        ),
    ]
