# Generated by Django 4.2.3 on 2023-07-13 02:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('position', models.CharField(choices=[('branch manager', 'Branch Manager'), ('cashier', 'Cashier'), ('supervisor', 'Supervisor'), ('technical engineer', 'Technical Engineer'), ('support staff', 'Support Staff')], max_length=48)),
                ('identificationNuber', models.CharField(max_length=48)),
            ],
        ),
    ]
